name: atelier4_o_erraouidate_iir5g2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  flutter_slidable: ^3.0.1
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
