// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHDbp23Puw3uXYdOvEhMXCNrJOd3O-bM',
    appId: '1:184785411660:web:c473006a5733ad3a129ee9',
    messagingSenderId: '184785411660',
    projectId: 'atelier-4-o-erraouidate-iir5g2',
    authDomain: 'atelier-4-o-erraouidate-iir5g2.firebaseapp.com',
    storageBucket: 'atelier-4-o-erraouidate-iir5g2.appspot.com',
    measurementId: 'G-WN3BPZPXNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1fk-JVsqe92D36gnAgoMfuWcvDjRAvs',
    appId: '1:184785411660:android:93ecfee43f6b5cb0129ee9',
    messagingSenderId: '184785411660',
    projectId: 'atelier-4-o-erraouidate-iir5g2',
    storageBucket: 'atelier-4-o-erraouidate-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9IcD3s3WjQMpYlxtzFE3w-ld0vmTDFAc',
    appId: '1:184785411660:ios:220d33f40e2da320129ee9',
    messagingSenderId: '184785411660',
    projectId: 'atelier-4-o-erraouidate-iir5g2',
    storageBucket: 'atelier-4-o-erraouidate-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4OErraouidateIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9IcD3s3WjQMpYlxtzFE3w-ld0vmTDFAc',
    appId: '1:184785411660:ios:30e1d268ab3db0ce129ee9',
    messagingSenderId: '184785411660',
    projectId: 'atelier-4-o-erraouidate-iir5g2',
    storageBucket: 'atelier-4-o-erraouidate-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4OErraouidateIir5g2.RunnerTests',
  );
}
